### PR TITLE
Gone.

### PR DESCRIPTION
**Pull request by HappyCord**
Where'd it go

### CODE REVIEW

**Comment by iamthewallrus** [comment]
Why do SPEDS like you open useless issues or pull requests on GitHub for attention?

**Comment by HappyCord** [comment]
> Why do SPEDS like you open useless issues or pull requests on GitHub for attention?

I was bored at school

**Comment by xeome** [comment]
Wow, that's very harmful; let's all give it a thumbs down. (!)

**Comment by daraul** [comment]
Easy fix: `git revert 9a8976190a427f08d9b088ff84e43b7a2328b040`

**Comment by krovellium** [comment]
why is this still open

**Comment by peter-dolkens** [comment]
> why is this still open

Because it's Gone, but not forgotten...

**Comment by Globaloffensive** [comment]
Where you gonna go carmack , ? Sir

**Pull request closed without merging**
